APT::FTPArchive::Release {
  Origin "ALPS";
  Label "ALPS";
  Suite "stable";
  Codename "stable";
  Architectures "amd64 arm64 armhf all";
  Components "main";
  Description "ALPS APT Repository";
};
